--drop table st_Artificial;
--drop table st_BedRockDimension;
--drop table st_SuperFicialThickness;
--drop table st_LandformsDimension;
--drop table st_FaultsDimension;
--drop table 	st_MassMovement;

create hadoop table st_Artificial
(	
GIS_UID int,
LEX	varchar(10),
LEX_D	varchar(30),
LEX_RCS	varchar(20),
RCS	varchar(20),
RCS_X	varchar(10),
RCS_D	varchar(30),
RANK	varchar(30),
BED_EQ	varchar(20),
BED_EQ_D varchar(20),
MB_EQ	varchar(20),
MB_EQ_D	varchar(20),
FM_EQ	varchar(5),
FM_EQ_D	varchar(20),
SUBGP_EQ varchar(20),	
SUBGP_EQ_D	varchar(20),
GP_EQ	varchar(10),
GP_EQ_D	varchar(30),
SUPGP_EQ	varchar(10),	
SUPGP_EQ_D	varchar(30),
MAX_TIME_D	varchar(20),
MIN_TIME_D	varchar(20),
MAX_TIME_Y	double,
MIN_TIME_Y	double,	
MAX_INDEX	double,
MIN_INDEX	double,
MAX_AGE	varchar(30),
MIN_AGE	varchar(30),
MAX_EPOCH	varchar(30),
MIN_EPOCH	varchar(30),
MAX_SUBPER varchar(30),
MIN_SUBPER varchar(30),
MAX_PERIOD	varchar(20),
MIN_PERIOD	varchar(20),
MAX_ERA	varchar(20),
MIN_ERA	varchar(20),
MAX_EON	varchar(20),
MIN_EON	varchar(20),
PREV_NAME	varchar(30),
BGSTYPE	varchar(20),
LEX_RCS_I	varchar(30),
LEX_RCS_D	varchar(50),
BGSREF	int,
BGSREF_LEX	int,
BGSREF_FM	int,
BGSREF_GP	int,
BGSREF_RK	int,
SHEET  varchar(10),
VERSION	varchar(10),
RELEASED varchar(12),	
NOM_SCALE int,	
NOM_OS_YR	int,
NOM_BGS_YR int,
MSLINK	int,
LEX_ROCK varchar(20),	
Easting float,
Northing float,
Latitude float,
Longitude float
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';
--select * from st_artificial;
load hadoop using file url 'sftp://biadmin:biadmin@bivm:22/home/biadmin/Desktop/data/SuperFicial/Artificial_Coordinates2.txt'    with SOURCE PROPERTIES ('field.delimiter'='\t') into table st_Artificial overwrite;

CREATE HADOOP TABLE 
st_MassMovement 
( 
GIS_UID int, 
LEX	varchar(10),
LEX_D	varchar(30),
LEX_RCS	varchar(20),
RCS	varchar(20),
RCS_X	varchar(10),
RCS_D	varchar(30),
RANK	varchar(30),
BED_EQ	varchar(20),
BED_EQ_D varchar(20),
MB_EQ	varchar(20),
MB_EQ_D	varchar(20),
FM_EQ	varchar(5),
FM_EQ_D	varchar(20),
SUBGP_EQ varchar(20),	
SUBGP_EQ_D	varchar(20),
GP_EQ	varchar(10),
GP_EQ_D	varchar(30),
SUPGP_EQ	varchar(10),	
SUPGP_EQ_D	varchar(30),
MAX_TIME_D	varchar(20),
MIN_TIME_D	varchar(20),
MAX_TIME_Y	double,
MIN_TIME_Y	double,	
MAX_INDEX	double,
MIN_INDEX	double,
MAX_AGE	varchar(30),
MIN_AGE	varchar(30),
MAX_EPOCH	varchar(30),
MIN_EPOCH	varchar(30),
MAX_SUBPER varchar(20),
MIN_SUBPER varchar(20),
MAX_PERIOD	varchar(20),
MIN_PERIOD	varchar(20),
MAX_ERA	varchar(20),
MIN_ERA	varchar(20),
MAX_EON	varchar(20),
MIN_EON	varchar(20),
PREV_NAME	varchar(30),
BGSTYPE	varchar(20),
LEX_RCS_I	varchar(30),
LEX_RCS_D	varchar(50),
BGSREF	int,
BGSREF_LEX	int,
BGSREF_FM	int,
BGSREF_GP	int,
BGSREF_RK	int,
SHEET	varchar(10),
VERSION	varchar(12),
RELEASED varchar(12),
NomScale float,
NomOsYear varchar(12),
NomBGSYear varchar(12),	
MSLINK	int,
LEX_ROCK varchar(20),	
Easting float,
Northing float,
Latitude float,
Longitude float
) 
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';
load hadoop using file url 'sftp://biadmin:biadmin@bivm:22/home/biadmin/Desktop/data/SuperFicial/massmovement_Coordinates2.txt'    with SOURCE PROPERTIES ('field.delimiter'='\t') into table st_MassMovement overwrite;

CREATE HADOOP TABLE 
st_FaultsDimension
( 
GIS_UID int, 
CATEGORY varchar(10), 
Feature varchar(30) , 
FeatureDesc varchar(100), 
FltNameC varchar(30),
FltNameDesc varchar(100),
SHEET	varchar(12),
VERSION	 varchar(12),
RELEASED varchar(12),
NomScale float,
NomOsYear varchar(12),
NomBGSYear varchar(12),
MSLink	int,
Easting float,
Northing float
--latitude float,
--longitude float  
)ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';
load hadoop using file url 'sftp://biadmin:biadmin@bivm:22/home/biadmin/Desktop/data/SuperFicial/fault_WithCoordinates2.txt'    with SOURCE PROPERTIES ('field.delimiter'='\t') into table st_FaultsDimension overwrite;

CREATE HADOOP TABLE 
st_LandformsDimension 
( 
LFID int, 
CATEGORY varchar(10),
Feature varchar(30) , 
FeatureDesc varchar(100), 
SHEET varchar(10),
VERSION	varchar(14),
RELEASED varchar(14),
NomScale float,
NomOsYear varchar(14),
NomBGSYear varchar(14),
MSLink	int,
Easting float,
Northing float,
Latitude float,
Longitude float
) 
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';
load hadoop using file url 'sftp://biadmin:biadmin@bivm:22/home/biadmin/Desktop/data/SuperFicial/landform_Coordinates2.txt'    with SOURCE PROPERTIES ('field.delimiter'='\t') into table st_LandformsDimension overwrite;

CREATE HADOOP TABLE 
st_SuperFicialThickness 
( SFTid int, 
LEX	varchar(10),
LEX_D	varchar(30),
LEX_RCS	varchar(20),
RCS	varchar(20),
RCS_X	varchar(10),
RCS_D	varchar(30),
RANK	varchar(30),
MAX_TIME_D	varchar(20),
MIN_TIME_D	varchar(20),
MAX_TIME_Y	double,
MIN_TIME_Y	double,
MAX_INDEX	double,
MIN_INDEX	double,
MAX_AGE	varchar(30),
MIN_AGE	varchar(30),
MAX_EPOCH	varchar(30),
MIN_EPOCH	varchar(30),
MAX_PERIOD	varchar(20),
MIN_PERIOD	varchar(20),
MAX_ERA	varchar(20),
MIN_ERA	varchar(20),
MAX_EON	varchar(20),
MIN_EON	varchar(20),
PREV_NAME	varchar(30),
BGSTYPE	varchar(20),
LEX_RCS_I	varchar(30),
LEX_RCS_D	varchar(50),
BGSREF	int,
BGSREF_LEX	int,
BGSREF_FM	int,
BGSREF_GP	int,
BGSREF_RK	int,
MSLINK	int,
LEX_ROCK varchar(20),	
Easting float,
Northing float,
Latitude float,
Longitude float
) 
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';
load hadoop using file url 'sftp://biadmin:biadmin@bivm:22/home/biadmin/Desktop/data/SuperFicial/superficial_Coordinates_UPD2.txt'    with SOURCE PROPERTIES ('field.delimiter'='\t') into table st_SuperFicialThickness overwrite;

CREATE HADOOP TABLE 
st_BedRockDimension 
( 
BRId int, 
LEX	varchar(10),
LEX_D	varchar(30),
LEX_RCS	varchar(20),
RCS	varchar(20),
RCS_X	varchar(10),
RCS_D	varchar(30),
RANK	varchar(30),
BED_EQ	varchar(20),
BED_EQ_D varchar(20),
MB_EQ	varchar(20),
MB_EQ_D	varchar(20),
FM_EQ	varchar(5),
FM_EQ_D	varchar(20),
SUBGP_EQ varchar(20),	
SUBGP_EQ_D	varchar(20),
GP_EQ	varchar(10),
GP_EQ_D	varchar(30),
SUPGP_EQ	varchar(10),	
SUPGP_EQ_D	varchar(30),
MAX_TIME_D	varchar(20),
MIN_TIME_D	varchar(20),
MAX_TIME_Y	double,
MIN_TIME_Y	double,
MAX_INDEX	double,
MIN_INDEX	double,
MAX_AGE	varchar(30),
MIN_AGE	varchar(30),
MAX_EPOCH	varchar(30),
MIN_EPOCH	varchar(30),
MAX_SUBPER	varchar(30),
MIN_SUBPER	varchar(30),
MAX_PERIOD	varchar(20),
MIN_PERIOD	varchar(20),
MAX_ERA	varchar(20),
MIN_ERA	varchar(20),
MAX_EON	varchar(20),
MIN_EON	varchar(20),
PREV_NAME	varchar(30),
BGSTYPE	varchar(20),
LEX_RCS_I	varchar(30),
LEX_RCS_D	varchar(50),
BGSREF	int,
BGSREF_LEX	int,
BGSREF_FM	int,
BGSREF_GP	int,
BGSREF_RK	int,
SHEET	varchar(14),
VERSION	varchar(14),
RELEASED varchar(14),	
NomScale float,
NomOsYear varchar(14),
NomBGSYear varchar(14),
MSLINK	int,
LEX_ROCK varchar(20),	
Easting float,
Northing float,
Latitude float,
Longitude float
) 
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';
load hadoop using file url 'sftp://biadmin:biadmin@bivm:22/home/biadmin/Desktop/data/SuperFicial/bedrock_WithCoordinates2.txt'    with SOURCE PROPERTIES ('field.delimiter'='\t') into table st_BedRockDimension overwrite;

